export { default as IpAddressWidget } from './IpAddressWidget'
export { default as QOTDWidget } from './QuoteOfTheDayWidget'
export { default as AdviceWidget } from './AdviceWidget'
export { default as KanyeQuoteWidget } from './KanyeQuote'
export { default as InspirationWidget } from './InspirationWidget'
